service: deploy
provider:
  name: aws
  runtime: go1.x
  layers:
    - !Ref ToolsLambdaLayer
  iamRoleStatements:
    - Effect: Allow
      Action: lambda:InvokeFunction
      Resource: !Join [':', ['arn', 'aws', 'lambda', '${self:provider.region}', !Ref 'AWS::AccountId', 'function', '${self:service}-${self:provider.stage}-*']]
  environment:
    DEPLOY_FUNCTION: ${self:service}-${self:provider.stage}-deploy
    LANG: en_US.UTF-8  # Building the site fails without this.
    WEBHOOK_SECRET: ${env:WEBHOOK_SECRET}
package:
  exclude:
    - ./**
  include:
    - ./bin/*
    - ./ssh.zip
layers:
  tools:
    name: ${self:service}-${self:provider.stage}-tools
    path: ./layer
    package:
      exclude:
        - ./**
      include:
        - ./bin/**
        - ./lib/**
functions:
  webhook:
    handler: ./bin/webhook
    events:
      - http: POST /deploy
  deploy:
    handler: ./bin/deploy
    timeout: 900
    memorySize: 3008
